CREATE TABLE usuarios_service.usuarios
(
    id_usuario       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom_usuario      VARCHAR(30)                             NOT NULL,
    ap_usuario       VARCHAR(30)                             NOT NULL,
    correo_usuario   VARCHAR(100)                            NOT NULL,
    telefono_usuario VARCHAR(12)                             NOT NULL,
    clave_usuario    VARCHAR(16)                             NOT NULL,
    CONSTRAINT pk_usuarios PRIMARY KEY (id_usuario)
);

ALTER TABLE usuarios_service.usuarios
    ADD CONSTRAINT uc_usuarios_clave_usuario UNIQUE (clave_usuario);

ALTER TABLE usuarios_service.usuarios
    ADD CONSTRAINT uc_usuarios_correo_usuario UNIQUE (correo_usuario);

ALTER TABLE usuarios_service.usuarios
    ADD CONSTRAINT uc_usuarios_telefono_usuario UNIQUE (telefono_usuario);